/** Declaration file generated by dts-gen */

export function serve(req: any, res: any, next: any): any;

export function setup(swaggerDoc: any, opts?: any, options?: any, customCss?: any, customfavIcon?: any, swaggerUrl?: any, customeSiteTitle?: any): any;

export namespace serve {
  const prototype: {
  };

}

export namespace setup {
  const prototype: {
  };

}

